include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    public_member_api_docs: ignore
    depend_on_referenced_packages: ignore
    one_member_abstracts: ignore
    
linter:
  rules:
    sort_pub_dependencies: false