name: monthly_dependencies
description: "A new Flutter package project."
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0

  flutter_svg: ^2.0.17
  lottie: ^3.3.1

  go_router: ^14.8.1  
  result_dart: ^2.1.0
  equatable: ^2.0.7
  
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  
  google_fonts: ^6.2.1
  
  easy_localization: ^3.0.7+1
  easy_localization_loader: ^2.0.2

  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0

flutter:

  uses-material-design: true