name: monthly_database
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: ^6.0.0 #Until isar is updated to 4.0.0

dependencies:
  flutter:
    sdk: flutter

  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.15   
  path_provider_platform_interface: ^2.1.2