include: package:very_good_analysis/analysis_options.yaml

formatter:
  trailing_commas: preserve

analyzer:
  errors:
    public_member_api_docs: ignore
    depend_on_referenced_packages: ignore
    one_member_abstracts: ignore 
    
linter:
  rules:
    sort_pub_dependencies: false